### ISSUE TITLE
Android problem

### ISSUE THREAD

**Issue by bohdan145** [ifsnow/react-native-networking-patch#2]
Does it work on Android ? 
My app just stuck on startup screen, because the request is not sent 
I've tried it on real phone and emulator, the results are the same, but iOS seems to be working fine.
I am on RN 0.59.10, android 7.1 and 9.0 tested

**Comment by ifsnow** [comment]
I created a sample empty project with v0.59.10 and just checked that `fetch` command works.

Please delete the Android build cache and try building again.

```bash
$ cd android
$ ./gradlew clean
```

**Comment by bohdan145** [comment]
It's weird because it works when i use debug js remotly
And btw i am using react-native-v8 instead of default JSC

**Comment by ifsnow** [comment]
Sorry, This was tested on JSC(default) and Hermes. I don't use `react-native-v8`, so it seems difficult to check.
